### ISSUE TITLE
Extract ExPlat from WordPress-Android to Automattic-Tracks-Android

### ISSUE THREAD

**Issue by RenanLukas** [Automattic/Automattic-Tracks-Android#112]
Extract [ExPlat implementation](https://github.com/wordpress-mobile/WordPress-Android/tree/trunk/WordPress/src/main/java/org/wordpress/android/util/experiments) from WordPress-Android to Automattic-Tracks-Android so it can also be used by [woocommerce-android](https://github.com/woocommerce/woocommerce-android) and other projects.

**Comment by wzieba** [comment]
Suggestion: can we make this as a separate module? I plan to extract `crashlogging`, arguments presented in #102
