### ISSUE TITLE
Send events to the server more often 

### ISSUE THREAD

**Issue by daniloercoli** [Automattic/Automattic-Tracks-Android#16]
We've had our first step in comparing Mixpanel and Track numbers, and seems that Tracks numbers are always lower (5% of delta) than the ones recorded in Mixpanel.

The Android library works in this way:
- We store events in the db, when the fixed limit of 10 events is reached, all events are read from the DB and sent to the server with a batch request. If the request fails events are re-enqueued in the DB.
- When the app is sent in background, all events are sent to the server. Doesn't matter how many events are in the queue. 

My hypothesis is that the app fails to push events (ie: a network error) when the "on background" event  happens, and then the user doesn't reopen the app in the next 5 days.
<b>Important note:  On the server events that are 5 days old or more are rejected.</b>

How to fix this:
1) We can create a service that runs in background and sends the events to the server, but we will have hard time justifying a background process just to send usage data over the Internet.
2) Be more aggressive, and send events to the server more often. ie: Change the 10 events limit, and lower it to 5.

Also removing the policy that 5 days old events are discarded on the server may help a lot.

cc @martinremy @astralbodies @xyu

**Comment by xyu** [comment]
Interesting that we are still seeing less events in Tracks then Mixpanel. Is there a way to show unique users instead of raw counts in Mixpanel? (I poked around and didn't see an option.) It would be interesting to know if we are also reporting lower unique users.

**Comment by daniloercoli** [comment]
@xyu Interesting...... Uniques users seem to be lower in Mixpanel!
![screen shot 2015-07-23 at 12 24 12](https://cloud.githubusercontent.com/assets/518232/8848176/9e6fd0b0-3135-11e5-94b2-4ff5dde166a7.png)
![screen shot 2015-07-23 at 12 25 06](https://cloud.githubusercontent.com/assets/518232/8848194/bf679ad2-3135-11e5-8de0-29b37d88ed88.png)

**Comment by gibrown** [comment]
@daniloercoli can we get individual users from Mixpanel? I wonder if we looked at all the events for 1000 users we could narrow in on a couple where there are big discrepancies and try and understand the use cases.

I feel like we need to determine if the difference is because across all users there are 5% fewer events vs 5% of users are not getting their events recorded. The latter seems more likely to be linked to the 5 day old events getting tossed.
