### ISSUE TITLE
Continuous integration setup

### ISSUE THREAD

**Issue by wzieba** [Automattic/Automattic-Tracks-Android#52]
Maybe w could add continuous integration setup to this library, WDYT @oguzkocer @jkmassel ?

I was thinking about two simple workflows/pipelines:
1. Basic check for commit - build and test
2. Release on new tag

If it's ok, I can help with that, I believe CircleCI is our choice for every CI/CD right?

**Comment by oguzkocer** [comment]
I think it'd be good to have the basic build and test, but I am reluctant about the release task since we'll have to replace Bintray very soon. I think we might go with Jitpack for this library for a little while, so maybe we should hold off on that task?

Yes, we use CircleCI.
