### ISSUE TITLE
Specify the WPCOM user ID in addition to login name

### ISSUE THREAD

**Issue by astralbodies** [Automattic/Automattic-Tracks-Android#6]
According to @skeltoac the `_ui` key is required for all user types - `_ul` is somewhat optional but should be sent in addition to the ID.

Code: https://github.com/Automattic/Automattic-Tracks-Android/blob/develop/AutomatticTracks/src/main/java/com/automattic/android/tracks/MessageBuilder.java#L106

**Comment by daniloercoli** [comment]
The `user_id` field is filled server side if we send the `user_login_name`. The same if we send `user_id`, `user_login_name` is filled server side.
